const LocationTypes = {
  FETCH_STATIONS_START: 'FETCH_STATIONS_START',
  FETCH_STATIONS_SUCCESS: 'FETCH_STATIONS_SUCCESS',
  FETCH_STATIONS_FAILURE: 'FETCH_STATIONS_FAILURE',
  SET_CURRENT_STATION_ID: 'SET_CURRENT_STATION_ID',
};

export default LocationTypes;
